export default {
  genreMapJson: [
    { prop: 'Action', label: '动作' },
    { prop: 'Adventure', label: '冒险' },
    { prop: 'Animation', label: '动画' },
    { prop: 'Children\'s', label: '儿童' },
    { prop: 'Comedy', label: '喜剧' },
    { prop: 'Crime', label: '犯罪' },
    { prop: 'Documentary', label: '纪录' },
    { prop: 'Drama', label: '情景' },
    { prop: 'Fantasy', label: '奇幻' },
    { prop: 'Film-Noir', label: '黑色' },
    { prop: 'Horror', label: '恐怖' },
    { prop: 'Musical', label: '音乐' },
    { prop: 'Mystery', label: '神秘' },
    { prop: 'Romance', label: '浪漫' },
    { prop: 'Sci-Fi', label: '科幻' },
    { prop: 'Thriller', label: '惊悚' },
    { prop: 'War', label: '战争' },
    { prop: 'Western', label: '西部' },
    { prop: 'unknown', label: '其他' },
  ],

  genreMap: {
    Action: '动作',
    Adventure: '冒险',
    Animation: '动画',
    'Children\'s': '儿童',
    Comedy: '喜剧',
    Crime: '犯罪',
    Documentary: '纪录',
    Drama: '情景',
    Fantasy: '奇幻',
    'Film-Noir': '黑色',
    Horror: '恐怖',
    Musical: '音乐',
    Mystery: '神秘',
    Romance: '浪漫',
    'Sci-Fi': '科幻',
    Thriller: '惊悚',
    War: '战争',
    Western: '西部',
    unknown: '其他',
  },

  genreConfigList: [
    {
      id: 0,
      left: '0px',
      top: '0px',
      height: '150px',
      width: '150px',
      lineHeight: '150px',
      fontSize: '22px',
      color: '#f6f5f7',
    }, {
      id: 1,
      left: '0px',
      top: '250px',
      height: '120px',
      width: '120px',
      lineHeight: '120px',
      fontSize: '20px',
      color: '#f6f5f7',
    }, {
      id: 2,
      left: '0px',
      bottom: '0px',
      height: '110px',
      width: '110px',
      lineHeight: '110px',
      fontSize: '20px',
      color: '#f6f5f7',
    }, {
      id: 3,
      left: '250px',
      top: '0px',
      height: '110px',
      width: '110px',
      lineHeight: '110px',
      fontSize: '20px',
      color: '#f6f5f7',
    }, {
      id: 4,
      left: '120px',
      top: '120px',
      height: '200px',
      width: '200px',
      lineHeight: '200px',
      fontSize: '28px',
      color: '#f6f5f7',
    }, {
      id: 5,
      left: '150px',
      bottom: '0px',
      height: '150px',
      width: '150px',
      lineHeight: '150px',
      fontSize: '20px',
      color: '#f6f5f7',
    }, {
      id: 6,
      left: '400px',
      top: '50px',
      height: '150px',
      width: '150px',
      lineHeight: '150px',
      fontSize: '24px',
      color: '#f6f5f7',
    }, {
      id: 7,
      left: '370px',
      top: '230px',
      height: '140px',
      width: '140px',
      lineHeight: '140px',
      fontSize: '24px',
      color: '#f6f5f7',
    }, {
      id: 8,
      left: '330px',
      bottom: '10px',
      height: '110px',
      width: '110px',
      lineHeight: '110px',
      fontSize: '18px',
      color: '#f6f5f7',
    }, {
      id: 9,
      left: '600px',
      top: '0px',
      height: '220px',
      width: '220px',
      lineHeight: '220px',
      fontSize: '30px',
      color: '#f6f5f7',
    }, {
      id: 10,
      left: '550px',
      top: '230px',
      height: '90px',
      width: '90px',
      lineHeight: '90px',
      fontSize: '18px',
      color: '#f6f5f7',
    }, {
      id: 11,
      left: '500px',
      bottom: '0px',
      height: '150px',
      width: '150px',
      lineHeight: '150px',
      fontSize: '22px',
      color: '#f6f5f7',
    }, {
      id: 12,
      left: '660px',
      top: '240px',
      height: '160px',
      width: '160px',
      lineHeight: '160px',
      fontSize: '20px',
      color: '#f6f5f7',
    }, {
      id: 13,
      left: '730px',
      bottom: '0px',
      height: '90px',
      width: '90px',
      lineHeight: '90px',
      fontSize: '18px',
      color: '#f6f5f7',
    }, {
      id: 14,
      right: '200px',
      top: '0px',
      height: '90px',
      width: '90px',
      lineHeight: '90px',
      fontSize: '20px',
      color: '#f6f5f7',
    }, {
      id: 15,
      right: '0px',
      top: '0px',
      height: '150px',
      width: '150px',
      lineHeight: '150px',
      fontSize: '24px',
      color: '#f6f5f7',
    }, {
      id: 16,
      right: '130px',
      top: '130px',
      height: '170px',
      width: '170px',
      lineHeight: '170px',
      fontSize: '28px',
      color: '#f6f5f7',
    }, {
      id: 17,
      right: '10px',
      top: '200px',
      height: '100px',
      width: '100px',
      lineHeight: '100px',
      fontSize: '18px',
      color: '#f6f5f7',
    }, {
      id: 18,
      right: '50px',
      bottom: '0px',
      height: '180px',
      width: '180px',
      lineHeight: '180px',
      fontSize: '24px',
      color: '#f6f5f7',
    },
  ],

  colors: [
    '#eb3b5a', '#fa8231', '#45aaf2', '#4b7bec', '#f7b731', '#a55eea', '#20bf6b', '#0fb9b1', '#fc5c65', '#2d98da',
  ],

  moviesConfigList: [
    {
      id: 0,
      left: '0px',
      top: '0px',
    }, {
      id: 1,
      left: '0px',
      bottom: '110px',
    }, {
      id: 2,
      left: '120px',
      top: '250px',
    }, {
      id: 3,
      left: '350px',
      top: '80px',
    }, {
      id: 4,
      left: '350px',
      bottom: '160px',
    }, {
      id: 5,
      right: '0px',
      top: '0px',
    }, {
      id: 6,
      right: '0px',
      bottom: '110px',
    }, {
      id: 7,
      right: '120px',
      top: '250px',
    }, {
      id: 8,
      right: '350px',
      top: '80px',
    }, {
      id: 9,
      right: '350px',
      bottom: '160px',
    },
  ],
};
